/**
 * Split spoken text into chunks that are synthesized in parallel and played back-to-back, so the
 * first sentence starts playing while the rest is still being generated by the TTS service.
 * Ported from backend/client/src/lib/speech.js.
 */

const SENTENCE_BOUNDARY = /(?<=[.!?…])\s+(?=\S)/u;
const MIN_SENTENCE_CHARS = 25;
// Common Indonesian abbreviations that end with a period but do not end a sentence
const ABBREVIATION_END =
  /(?:\b(?:PT|Tbk|CV|Bpk|Ibu|Sdr|Sdri|dr|Dr|Ir|Drs|Prof|No|Jl|Kab|Kec|Prov|a\.n|d\.a|dll|dsb|tgl|thn|jam)\.)$/u;

export function splitForSpeech(
  text: string | null | undefined,
  { maxChars = 220, maxChunks = 4 }: { maxChars?: number; maxChunks?: number } = {},
): string[] {
  const clean = (text ?? "").trim();
  if (!clean) return [];
  if (clean.length <= MIN_SENTENCE_CHARS * 2) return [clean];

  const sentences: string[] = [];
  for (const raw of clean.split(SENTENCE_BOUNDARY)) {
    const s = raw.trim();
    if (!s) continue;
    const prev = sentences[sentences.length - 1];
    if (prev !== undefined && (prev.length < MIN_SENTENCE_CHARS || ABBREVIATION_END.test(prev))) {
      sentences[sentences.length - 1] = `${prev} ${s}`;
    } else {
      sentences.push(s);
    }
  }
  if (sentences.length <= 1) return [clean];

  const chunks = [sentences[0]];
  let current = "";
  for (const s of sentences.slice(1)) {
    if (current && current.length + s.length + 1 > maxChars) {
      chunks.push(current);
      current = s;
    } else {
      current = current ? `${current} ${s}` : s;
    }
  }
  if (current) chunks.push(current);

  if (chunks.length > maxChunks) {
    const head = chunks.slice(0, maxChunks - 1);
    head.push(chunks.slice(maxChunks - 1).join(" "));
    return head;
  }
  return chunks;
}

/** ElevenLabs-style audio tags like "[warmly]" must never be shown on screen. */
export const stripSpeechTags = (text: string | null | undefined): string =>
  (text ?? "").replace(/\[[A-Za-z][A-Za-z '-]{0,40}\]\s*/g, "").replace(/\s{2,}/g, " ").trim();
